version: '3.5'

services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
    environment:
      PGRST_DB_URI: postgres://postgres:mysecretpassword@postgres:5432/postgres
      PGRST_DB_SCHEMA: cosims
      PGRST_DB_ANON_ROLE: web_anonymous
    networks:
      - postgres

  postgres:
    image: cosims-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - postgres
    
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/

networks:
  postgres:
    driver: bridge
  # overload default values to be able to start database with VPN running,
  #  comes from conflicts happening between VPN and docker-compose
    ipam:
      config:
        - subnet: 172.18.0.0/16
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
    